### PR TITLE
Fix oneof validation

### LINKED ISSUE #32: Oneof validation
#### Summary

Only set oneof should be validated if not explicitly specified

#### Steps to Reproduce

1. Generate validation code for a oneof

#### What do you see now?

If no explicit path is supplied to the validator of a oneof, it defaults to validate *all* possible oneofs

#### What do you want to see instead?

If no explicit path is supplied to the validator of a oneof, it should only validate the one, which set

#### How do you propose to implement this?

Check, which oneof is set and validate it

#### Can you do this yourself and submit a Pull Request?

yes

### PR DESCRIPTION
**Pull request by rvolosatovs**
#### Summary

Closes #32 

#### Changes

- Add testcase for #32 
- Fix oneof validation template https://github.com/TheThingsIndustries/protoc-gen-validate/commit/a8c217170afa3099ab9ddfabf8988b588afdc2b5

### CODE REVIEW

File: main_test.go [hunk 1]
```diff
@@ -561,7 +561,43 @@ func TestValidateFields(t *testing.T) {
...
+					A: &testdata.Test_TestNested_TestNestedNested{
+						A: 42,
+						Test_TestNested_TestNestedNested_TestNestedNestedEmbed2: testdata.Test_TestNested_TestNestedNested_TestNestedNestedEmbed2{
+							NestedField_2: 2,
+						},
+					},
+					C: func(v time.Duration) *time.Duration { return &v }(43 * time.Second),
+				},
+			},
+			ErrorAssertion: func(t *testing.T, err error) bool { return assertions.New(t).So(err, should.BeError) },
```
Comment (rvolosatovs) [inline main_test.go]: We now catch this: https://github.com/TheThingsIndustries/protoc-gen-fieldmask/pull/33/files#diff-b99ccde9afa136346460d20e6a4482d4R63
